const cities = [
    { title: "Vilnius", enum: "vilnius" },
    { title: "Kaunas", enum: "kaunas" },
    { title: "Klaipėda", enum: "klaipeda" },
    { title: "Šiauliai", enum: "siauliai" },
    { title: "Panevežys", enum: "panevezys" },
    { title: "Alytus", enum: "alytus" },
    { title: "Marijampolė", enum: "marijampole" },
    { title: "Mažeikiai", enum: "mazeikiai" },
    { title: "Jonava", enum: "jonava" },
    { title: "Utena", enum: "utena" },
    { title: "Neringa", enum: "neringa" },
    { title: "Pagėgiai", enum: "pagegiai" },
    { title: "Palanga", enum: "palanga" },
    { title: "Kalvarija", enum: "kalvarija" },
    { title: "Rietavas", enum: "rietavas" },
    { title: "Birštonas", enum: "birstonas" },
    { title: "Druskininkai", enum: "druskininkai" },
    { title: "Kazlų Rūda", enum: "kazluruda" },
    { title: "Elektrėnai", enum: "elektrenai" },
    { title: "Visaginas", enum: "visaginas" },
    { title: "Akmenės r.", enum: "akmenes_rajonas" },
    { title: "Alytaus r.", enum: "alytaus_rajonas" },
    { title: "Anykščių r.", enum: "anyksciu_rajonas" },
    { title: "Biržų r.", enum: "birzu_rajonas" },
    { title: "Ignalinos r.", enum: "ignalinos_rajonas" },
    { title: "Jonavos r.", enum: "jonavos_rajonas" },
    { title: "Joniškio r.", enum: "joniskio_rajonas" },
    { title: "Jurbarko r.", enum: "jurbarko_rajonas" },
    { title: "Kaišiadorių r.", enum: "kaisiadoriu_rajonas" },
    { title: "Kauno r.", enum: "kauno_rajonas" },
    { title: "Kėdainių r.", enum: "kedainiu_rajonas" },
    { title: "Kelmės r.", enum: "kelmes_rajonas" },
    { title: "Klaipėdos r.", enum: "klaipedos_rajonas" },
    { title: "Kretingos r.", enum: "kretingos_rajonas" },
    { title: "Kupiškio r.", enum: "kupiskio_rajonas" },
    { title: "Lazdijų r.", enum: "lazdiju_rajonas" },
    { title: "Pakruojo r.", enum: "pakruojo_rajonas" },
    { title: "Mažeikių r.", enum: "mazeikiu_rajonas" },
    { title: "Molėtų r.", enum: "moletu_rajonas" },
    { title: "Panevėžio r.", enum: "panevezio_rajonas" },
    { title: "Pasvalio r.", enum: "pasvalio_rajonas" },
    { title: "Plungės r.", enum: "plunges_rajonas" },
    { title: "Prienų r.", enum: "prienu_rajonas" },
    { title: "Radviliškio r.", enum: "radviliskio_rajonas" },
    { title: "Raseinių r.", enum: "raseiniu_rajonas" },
    { title: "Rokiškio r.", enum: "rokiskio_rajonas" },
    { title: "Skuodo r.", enum: "skuodo_rajonas" },
    { title: "Šakių r.", enum: "sakiu_rajonas" },
    { title: "Šalčininkų r.", enum: "salcininku_rajonas" },
    { title: "Šiaulių r.", enum: "siauliu_rajonas" },
    { title: "Šilalės r.", enum: "silales_rajonas" },
    { title: "Šilutės r.", enum: "silutes_rajonas" },
    { title: "Širvintų r.", enum: "sirvintu_rajonas" },
    { title: "Švenčionių r.", enum: "svencioniu_rajonas" },
    { title: "Tauragės r.", enum: "taurages_rajonas" },
    { title: "Telšių r.", enum: "telsiu_rajonas" },
    { title: "Trakų r.", enum: "trakus_rajonas" },
    { title: "Ukmergės r.", enum: "ukmerges_rajonas" },
    { title: "Utenos r.", enum: "utenos_rajonas" },
    { title: "Varėnos r.", enum: "varenos_rajonas" },
    { title: "Vilkaviškio r.", enum: "vilkaviskio_rajonas" },
    { title: "Vilniaus r.", enum: "vilniaus_rajonas" },
    { title: "Zarasų r.", enum: "zarasu_rajonas" },
  ];
  
  export default cities;